WORKERS: 0
PRINT_FREQ: 10
WORK_DIR: 'E:/python_project/HKD_mobilenetv2/cfg/'
DATASET:
  DATASET: 'coco'
  ROOT: "E:/python_project/Dataset/COCO/"

  TEST_SET: 'val2017'
  TEST_FILE: 'val2017/annotations/person_keypoints_val2017.json'
  TRAIN_SET: 'train2017'
  TRAIN_FILE: 'train2017/annotations/person_keypoints_train2017.json'
#  TRAIN_SET: 'val2017'
#  TRAIN_FILE: 'annotations/person_keypoints_val2017.json'
  FLIP: true
  ROT_FACTOR: 45
  SCALE_FACTOR: 0.3
  SCALE_RATE: 1.25
  JOINT_IDS: [ 0, 1, 2, 3,4,5,6,7,8,9,10,11,12,13,14,15,16 ]
  FLIP_PAIRS: [ [ 1, 2 ], [ 3, 4 ], [ 5, 6 ], [ 7, 8 ], [ 9, 10 ], [ 11, 12 ], [ 13, 14 ], [ 15, 16 ] ]
  SKELETON: [ [ 15, 13 ], [ 13, 11 ], [ 16, 14 ], [ 14, 12 ], [ 11, 12 ], [ 5, 11 ], [ 6, 12 ], [ 5, 6 ], [ 5, 7 ],[ 6, 8 ], [ 7, 9 ], [ 8, 10 ], [ 0, 1 ], [ 0, 2 ], [ 1, 3 ], [ 2, 4 ] ]
  SELECT_DATA: False
MODEL:
  NAME: 'model_mobilenet_v2'
  TARGET_TYPE: 'gaussian'
  #  TARGET_TYPE: 'offset'
  PRETRAINED: 'E:\python_project\HKD_mobilenetv2\pretrained\mobilenet_v2-b0353104.pth'
  IMAGE_SIZE:
    - 192
    - 256
  NUM_JOINTS: 17
  EXTRA:
    HEATMAP_SIZE:
      - 48
      - 64
    SIGMA: 2
    FINAL_CONV_KERNEL: 1
    DECONV_WITH_BIAS: false
    NUM_DECONV_LAYERS: 3
    NUM_DECONV_FILTERS:
      - 128
      - 128
      - 128
    NUM_DECONV_KERNELS:
      - 4
      - 4
      - 4
    NUM_LAYERS: 18
    WIDTH_MULT: 1.0
LOSS:
  USE_TARGET_WEIGHT: true
  KPD: 10
TRAIN:
  BATCH_SIZE: 64
  SHUFFLE: true
  BEGIN_EPOCH: 0
  END_EPOCH: 1
  RESUME: false
  OPTIMIZER: 'sgd'
  LR: 0.001
  LR_FACTOR: 0.1
  LR_STEP:
    - 20
    - 40
  WD: 0.0001
  GAMMA1: 0.99
  GAMMA2: 0.0
  MOMENTUM: 0.9
  NESTEROV: false
TEST:
  BATCH_SIZE: 64
  COCO_BBOX_FILE: 'data/coco/person_detection_results/COCO_val2017_detections_AP_H_56_person.json'
  BBOX_THRE: 1.0
  FLIP_TEST: true
  IMAGE_THRE: 0.0
  IN_VIS_THRE: 0.2
  MODEL_FILE: ''
  NMS_THRE: 1.0
  OKS_THRE: 0.9
  USE_GT_BBOX: true
  SHIFT_HEATMAP: false
  POST_PROCESS: true
DEBUG:
  DEBUG: true
  SAVE_BATCH_IMAGES_GT: true
  SAVE_BATCH_IMAGES_PRED: true
  SAVE_HEATMAPS_GT: true
  SAVE_HEATMAPS_PRED: true
